GET http://localhost:3001/api/notes

### 
GET http://localhost:3001/api/notes/6523b864e4596802efa73519

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "address": "a1",
    "title": "New Note Title",
    "content": "This is the content of the new note.",
    "citation": "New Note Citation"
}

###
PUT http://localhost:3001/api/notes/6523b864e4596802efa73519
Content-Type: application/json

{
    "address": "Updated Address",
    "title": "Updated Title",
    "content": "Updated Content",
    "citation": "Updated Citation"
}

###
DELETE http://localhost:3001/api/notes/6523b378e4596802efa734fd



