GET http://localhost:3001/api/notes

### 
GET http://localhost:3001/api/notes/652380325cbac88a4d37b768

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "address": "a1",
    "title": "New Note Title",
    "content": "This is the content of the new note.",
    "citation": "New Note Citation"
}

###
PUT http://localhost:3001/api/notes/652380325cbac88a4d37b768
Content-Type: application/json

{
    "address": "Updated Address",
    "title": "Updated Title",
    "content": "Updated Content",
    "citation": "Updated Citation"
}

###
DELETE http://localhost:3001/api/notes/6523b70de4596802efa7350c



